data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjM=
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXNpbmlhc3RvcmFnZWFjY291bnQ7QWNjb3VudEtleT1PQ2NpYUgzRmdmTlBTZ3Rnc3hlME1lN0xCZHhOTWFaSlNYWkhPU05vSVNuVnMybjNCMGJhdFdwRUZBZC9nR0lQUm44eWg3V0R3NXVGZzBnQXYzck81dz09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  APPINSIGHTS_INSTRUMENTATIONKEY: YmE5ZTZjMTMtMGVlNi00NGU5LWE3NWUtYWIxNmQ2ZTdhNzQw
  DBConnectionMongo: bW9uZ29kYjovL21hY2hvY29zbW9zZGI6RDRQTHlhbk15elZOdnR4aHRpMDRJR0YxZkc1bDllOWhHbFdRUUhMRmJXNkEydUtkU1Yxc3lPaW93cW51TGdvOTJEaXdzN3REMFFtTVcwUTZ1N1VxUUE9PUBtYWNob2Nvc21vc2RiLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImcmV0cnl3cml0ZXM9ZmFsc2UmbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AbWFjaG9jb3Ntb3NkYkA=
  APPLICATIONINSIGHTS_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PWJhOWU2YzEzLTBlZTYtNDRlOS1hNzVlLWFiMTZkNmU3YTc0MDtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL3dlc3R1cy0wLmluLmFwcGxpY2F0aW9uaW5zaWdodHMuYXp1cmUuY29tLw==
  connection: RW5kcG9pbnQ9c2I6Ly9ldmVudGh1Ym5hbWVzcGFjZXVkYWFzc2lnbi5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PVN6R241RVdhUzJwQVRMQnNkc20xQUI1cTAyYm10SlhrclkvVjE5VjZSMW89
apiVersion: v1
kind: Secret
metadata:
  name: machoaks
---

